name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
        postgres:
          image: postgres:latest
          env:
            POSTGRES_DB: jobParser
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: "1234"
          ports:
            - 5432:5432

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        sudo apt-get update && apt-get install -y \
        chromium \
        chromium-driver

    - name: Run tests
      run: |
        pytest app_test.py -v